# Data sources
We download our dataset from the CDC website, and our data come from three sources inside the CDC website. The first is the statistical data from [U.S. Diabetes Surveillance System](https://gis.cdc.gov/grasp/diabetes/DiabetesAtlas.html). The second type of data is derived from the questionnaire result from [National Center for Health Statistics](https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Questionnaire). The third one is about the "Underlying Cause of Death" data from [CDC WONDER](https://wonder.cdc.gov/ucd-icd10.html).  

The first data source is from the [U.S. Diabetes Surveillance System](https://gis.cdc.gov/grasp/diabetes/DiabetesAtlas.html). You can see some choice of filter options on this page, which are National, state, county, and other indicators. For the map plot, we want to explore the diabetes distribution in the U.S., so we filter by state and choose the total number of diabetes patients. The original data downloaded from CDC is consist of 54 states every year from 2000 to 2018, and we select the year 2018 to draw our map. The types of variables we use are both categorical and discrete data. Similarly, we can classify by age, gender, race, and education to download the data. In this data source, there is also the Social Determinants option that contains Risk Factors for Diabetes including obesity, physical inactivity, social vulnerability index, etc. We discover some issues with this Social Determinants data class, which is there is no state-level data under this classification, all the data are at the county level. Another major issue with this data source is that we need to do filtering on the website. This interactive way of exploring data might be user-friendly for some people, but it does not allow us to download the entire data we need in one file. So, all our data is in pieces with a lot of CSV files.  

The second data source is the [National Center for Health Statistics](https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Questionnaire). On this page, we can see the questionnaire on diabetes from the year 1999 to 2020. This questionnaire contains around 50 questions because the NCHS add some questions in recent years. There are around 8000 participants involved every year, so we have about 8000 entries in our data. We have a problem with the newest data for the year 2017 to 2020, which is the NHANES program suspended field operations in March 2020 due to the coronavirus disease 2019 pandemic. As a result, data collection for the NHANES 2019-2020 cycle was not completed. Therefore when doing our analysis using this data, we use the results from 2017 to 2018.  

The third data source is [CDC WONDER](https://wonder.cdc.gov/ucd-icd10.html). On this page, you can see many choices of options to filter the cause of death. We are mainly interested in the death number caused by diabetes and diabetes-related complications, so in the select cause of death part, we enter “diabetes” to filter the death cases caused by diabetes. We get the categorical variables for death reasons under diabetes and discrete variables for the death number. One issue about this website is that it only allows results with a maximum of 75,000 rows. But if we want to add all the filtering options we need, then the data will exceed the 75,000 rows. So we have to filter several times to get the data we need. 
