# Data transformation
```{r}
# map data
diabetes1 <- read.csv("DiabetesAtlasData-map.csv",header = FALSE)
diabetes1 <- diabetes1[3:1029,]
names(diabetes1) <- diabetes1[1,]
diabetes1 <- diabetes1[-1,]
```

```{r}
# mosaic data
diabetes_genders <- read.csv("DiabetesAtlasData_gender.csv",skip=2)
diabetes_age <- read.csv("DiabetesAtlasData_age.csv",skip=2)
diabetes_race <- read.csv("DiabetesAtlasData_race.csv",skip=2)
diabetes_education <- read.csv("DiabetesAtlasData_education.csv",skip=2)
diabetes_genders <- diabetes_genders[1:20,1:6]
diabetes_age <- diabetes_age[1:20,1:13]
diabetes_race <- diabetes_race[1:20,1:13]
diabetes_education <- diabetes_education[1:20,1:10]

library(magrittr)
age <- diabetes_age %>% 
  dplyr::select(Year,`X18.44...Percentage`,`X45.64...Percentage`,`X65.74...Percentage`,
       `X75....Percentage`)
colnames(age) <- c("Year","18-44","45-64","65-74","over74")

gender <- diabetes_genders %>% 
  dplyr::select(Year,`Male...Percentage`,`Female...Percentage`)
colnames(gender) <- c("Year","Male","Female")

race <- diabetes_race %>% 
  dplyr::select(Year,`Non.Hispanic.White...Percentage`,`Non.Hispanic.Black...Percentage`,
                `Non.Hispanic.Asian...Percentage`,`Hispanic...Percentage`)
colnames(race) <- c("Year","White","Black","Asian","Hispanic")

education <- diabetes_education %>% 
  dplyr::select(Year,`X..High.School...Percentage`,`High.School...Percentage`,
                `X..High.School...Percentage.1`)
colnames(education) <- c("Year","< High School","High School",
                      "> High School")
```
```{r}
# Cleveland Dot Plot data
library(readr)
death <- read_tsv("Underlying Cause of Death, 1999-2020.txt")
death <- death[1:10383,2:14]
```

```{r}
# parallel coordinate plot
DiagnosedDiabetes<- read.csv("DiagnosedDiabetes.csv",skip = 2)
Obesity <- read.csv("Obesity.csv",skip = 2)
PhysicalActivity<- read.csv("PhysicalActivity.csv",skip = 2)
```


