# Results

```{r}
# 1st plot: map
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(choroplethr)
library(choroplethrMaps)

diabetes1$Percentage <- as.numeric(diabetes1$Percentage)

df_diabetes1 <- diabetes1 %>% 
  filter(Year=="2018") %>% 
  transmute(region = tolower(`State`), value = Percentage) %>% 
  as.data.frame()
state_choropleth(df_diabetes1,num_colors = 9,legend = "Percentage",
                 title = "Percentage of Diagnosed Diabetes: 2018 by State")
```



```{r, fig.height=6, fig.width=10}
# 2nd plot: time series facet plot
low <- df_diabetes1[order(df_diabetes1$value),]$region[1:6]
high <- df_diabetes1[order(df_diabetes1$value,decreasing=T),]$region[1:6]

library(ggplot2)
library(zoo)
library(forcats)
df_diabetes2 <- diabetes1 %>%
  dplyr::select(Year,State,Percentage) %>% 
  filter(State=="Colorado"|State=="Utah"|State=="Massachusetts"|State=="Wisconsin"|
           State=="Wyoming"|State=="West Virginia"|State=="Alabama"|State=="Mississippi"|
           State=="Louisiana"|State=="Arkansas")
df_diabetes2$Year <- as.numeric(df_diabetes2$Year)
df_diabetes2$State <- fct_relevel(df_diabetes2$State,"Colorado","Utah","Massachusetts",
                                  "Wisconsin","Wyoming","West Virginia","Alabama",
                                  "Mississippi","Louisiana","Arkansas")
ggplot(df_diabetes2,aes(Year,Percentage))+
  geom_line()+
  facet_wrap(~State,nrow=2)+
  labs(title="Change of Diagnosed Diabetes Percentage: 2000-2018 ",
       subtitle = "Top: 5 States with the Lowest Diabetes Percentage in 2018
Bottom: 5 States with the Highest Diabetes Percentage in 2018")+
  theme_gray(16)
```

```{r, fig.height=6, fig.width=8}
# 3rd plot: cleveland dot plot
death_state <- death %>% 
  group_by(State) %>% 
  summarise(Freq=sum(Deaths)/sum(Population)*100000)
ggplot(death_state, aes(x = Freq, y = forcats::fct_reorder(State, Freq))) +
  geom_point(color = "blue") +
  ggtitle("Death due to Diabetes per 100000 People") +
  xlab("Number of Deaths")+
  ylab("") +
  theme_linedraw()
```

```{r}
# 4th plot: mosaic
library(magrittr)
age_2018 <- age %>% filter(Year=="2018")
age_2018 <- age_2018[,-1]
age_2018 <- cbind(Diabetes=c("Yes"),age_2018)
age_2018[nrow(age_2018)+1,] <- c("No",100-age_2018[[2]],100-age_2018[[3]],
                                 100-age_2018[[4]],100-age_2018[[5]])
age_2018$`18-44` <-  as.numeric(age_2018$`18-44`)
age_2018$`45-64` <-  as.numeric(age_2018$`45-64`)
age_2018$`65-74` <-  as.numeric(age_2018$`65-74`)
age_2018$over74 <-  as.numeric(age_2018$over74)

gender_2018 <- gender %>% filter(Year=="2018")
gender_2018 <- gender_2018[,-1]
gender_2018 <- cbind(Diabetes=c("Yes"),gender_2018)
gender_2018[nrow(gender_2018)+1,] <- c("No",100-gender_2018[[2]],100-gender_2018[[3]])
gender_2018$Male <-  as.numeric(gender_2018$Male)
gender_2018$Female <-  as.numeric(gender_2018$Female)

race_2018 <- race %>% filter(Year=="2018")
race_2018 <- race_2018[,-1]
race_2018 <- cbind(Diabetes=c("Yes"),race_2018)
race_2018[nrow(race_2018)+1,] <- c("No",100-race_2018[[2]],100-race_2018[[3]],
                                 100-race_2018[[4]],100-race_2018[[5]])
race_2018$White<-  as.numeric(race_2018$White)
race_2018$Black <-  as.numeric(race_2018$Black)
race_2018$Asian <-  as.numeric(race_2018$Asian)
race_2018$Hispanic <-  as.numeric(race_2018$Hispanic)

education_2018 <- education %>% filter(Year=="2018")
education_2018 <- education_2018[,-1]
education_2018 <- cbind(Diabetes=c("Yes"),education_2018)
education_2018[nrow(education_2018)+1,] <- c("No",100-education_2018[[2]],100-education_2018[[3]],100-education_2018[[4]])
education_2018$`< High School`<-  as.numeric(education_2018$`< High School`)
education_2018$`High School` <-  as.numeric(education_2018$`High School`)
education_2018$`> High School` <-  as.numeric(education_2018$`> High School`)


age_mosaic <- age_2018 %>%
  gather(key = "Age", value = "Freq", -Diabetes)
gender_mosaic <- gender_2018 %>%
  gather(key = "Gender", value = "Freq", -Diabetes)
race_mosaic <- race_2018 %>%
  gather(key = "Race", value = "Freq", -Diabetes)
education_mosaic <- education_2018 %>%
  gather(key = "Education", value = "Freq", -Diabetes)

race_mosaic$Race <- forcats::fct_relevel(race_mosaic$Race,"White","Black","Asian","Hispanic")
education_mosaic$Education <- forcats::fct_relevel(education_mosaic$Education,"< High School",
                                          "High School","> High School")
```

```{r, fig.height=10, fig.width=10}
# 4th plot: mosaic plot
library(gridExtra)
library(vcd)
g1 <- grid.grabExpr(mosaic(Diabetes ~ Age, direction = c("v", "h"), age_mosaic,
       highlighting_fill = c("grey80", "cornflowerblue")))
g2 <- grid.grabExpr(mosaic(Diabetes ~ Gender, direction = c("v", "h"), gender_mosaic,
       highlighting_fill = c("grey80", "cornflowerblue")))
g3 <- grid.grabExpr(mosaic(Diabetes ~ Race, direction = c("v", "h"), race_mosaic,
       highlighting_fill = c("grey80", "cornflowerblue")))
g4 <- grid.grabExpr(mosaic(Diabetes ~ Education, direction = c("v", "h"), education_mosaic,
       highlighting_fill = c("grey80", "cornflowerblue")))
grid.arrange(g1,g2,g3,g4)
```
```{r}
# 5th plot: histogram
library(foreign)
questionnaire18 <- read.xport("17_18.XPT")
diabetes_yes <- questionnaire18[questionnaire18$DIQ010==1,]
diabetes_first_age <- diabetes_yes[!is.na(diabetes_yes$DID040),]
diabetes_first_age1 <- diabetes_first_age[!diabetes_first_age$DID040==999,]
diabetes_first_age1 <- diabetes_first_age1[!diabetes_first_age1$DID040==666,]

ggplot(diabetes_first_age1, aes(DID040)) +
  geom_histogram(bins = 40,color = "wheat4", fill = "pink")+
  ggtitle("Age when first told you had diabetes")+
  xlab("Age")+
  theme_gray(16)

```
```{r, fig.height=4, fig.width=10}
# 6th Heatmap
death$DeathCode <- substr(death$`Cause of death Code`,1,3)

death_age_code <- death%>%
  group_by(`Ten-Year Age Groups Code`,
           DeathCode)%>%
  summarize(Freq=sum(Deaths)/sum(Population)*100000) %>% 
  ungroup() %>% 
  as.data.frame()

death_age_code[nrow(death_age_code)+1,] <- c("15-24","E11",0)
death_age_code[nrow(death_age_code)+1,] <- c("5-14","E10",0)
death_age_code[nrow(death_age_code)+1,] <- c("5-14","E11",0)
death_age_code$Freq <- as.numeric(death_age_code$Freq)

death_age_code$`Ten-Year Age Groups Code` <-  fct_relevel(death_age_code$`Ten-Year Age Groups Code`,"5-14","15-24","25-34","35-44","45-54","55-64","65-74","75-84","85+")
E10 <- death_age_code %>%
  filter(DeathCode=="E10") %>% 
  mutate(Reason="Insulin-dependent 
         diabetes")
E11 <- death_age_code %>%
  filter(DeathCode=="E11") %>% 
  mutate(Reason="Non-insulin-dependent 
         diabetes")
E14 <- death_age_code %>%
  filter(DeathCode=="E14") %>% 
  mutate(Reason="Unspecified 
         diabetes")
death_age_code <- rbind(E10,E11,E14)
death_age_code$Reason <- fct_relevel(death_age_code$Reason,"Unspecified 
         diabetes",
                                     "Non-insulin-dependent 
         diabetes",
                                     "Insulin-dependent 
         diabetes")
ggplot(death_age_code, aes(`Ten-Year Age Groups Code`, Reason, fill = Freq)) + 
  geom_tile(color = "white")+
  coord_equal()+
  scale_fill_viridis_c(direction = -1)+
  xlab("Age Groups")+
  ylab("Cause of Death")+
  ggtitle("Underlying Cause of Death by Diabetes")+
  theme_gray(16)
```


```{r}
# 7th plot: boxplot
A1C_level <- diabetes_yes[!is.na(diabetes_yes$DIQ280),]
A1C_level <- A1C_level[!A1C_level$DIQ280==777,]
A1C_level <- A1C_level[!A1C_level$DIQ280==999,]
A1C_level <- A1C_level[!is.na(A1C_level$DID260),]
A1C_level <- A1C_level[!A1C_level$DID260==999,]
A1C_level <- A1C_level %>% 
  dplyr::select(DIQ280,DID260)
A1C_level$DID260 <- as.character(A1C_level$DID260)
A1C_level$DID260 <- fct_relevel(A1C_level$DID260,"0","1","2","3","4","5","6","7","10")
ggplot(A1C_level, aes(DID260, DIQ280)) + 
  geom_boxplot() + 
  ylab("A1C level")+
  xlab("Times of checking blood sugar")+
  theme_grey(16)

```

```{r, fig.height=8, fig.width=10}
# 8th plot: parallel coordinate plot
DiagnosedDiabetes_new <- DiagnosedDiabetes_new %>% dplyr::select(State,Percentage)
colnames(DiagnosedDiabetes_new) <- c("State","Diagnosed
Diabetes")
Obesity_new <- Obesity_new %>% dplyr::select(State,Percentage)
colnames(Obesity_new) <- c("State","Obesity")
PhysicalInactivity_new <- PhysicalInactivity_new %>% dplyr::select(State,Percentage)
colnames(PhysicalInactivity_new) <- c("State","Physical
Inactivity")
HypertensionAwareness_new <- HypertensionAwareness_new  %>% dplyr::select(State,Percentage)
colnames(HypertensionAwareness_new) <- c("State","Hypertension
Awareness")
HighCholesterolAwareness_new <- HighCholesterolAwareness_new %>% dplyr::select(State,Percentage)
colnames(HighCholesterolAwareness_new) <- c("State","High Cholesterol
Awareness")

diabetes_parallel_new <- left_join(DiagnosedDiabetes_new,Obesity_new)
diabetes_parallel_new <- left_join(diabetes_parallel_new,PhysicalInactivity_new)
diabetes_parallel_new <- left_join(diabetes_parallel_new,HypertensionAwareness_new)
diabetes_parallel_new <- left_join(diabetes_parallel_new,HighCholesterolAwareness_new)

library(GGally) 
diabetes_parallel_new <- diabetes_parallel_new[-1,]
ggparcoord(diabetes_parallel_new, columns = c(5,2,6,3,4))+
  theme_grey(16)
```


