# Interactive component
```{r}
library(plotly)

death_year <- death_year %>% 
  dplyr::filter(Year==2000|Year==2001|Year==2002|Year==2003|Year==2004|Year==2005|
           Year==2006|Year==2007|Year==2008|Year==2009|Year==2010|Year==2011|
           Year==2012|Year==2013|Year==2014|Year==2015|Year==2016|Year==2017|
           Year==2018)
diabetes1$Year <- as.numeric(diabetes1$Year)
diabetes2 <- diabetes1[!diabetes1$State=="Guam",]
diabetes2 <- diabetes2[!diabetes2$State=="Puerto Rico",]
diabetes2 <- diabetes2[!diabetes2$State=="Virgin Islands of the U.S.",]
diabetes2 <- diabetes2[1:968,]
diabetes_death <-  left_join(death_year,diabetes2)
diabetes_death <- diabetes_death %>% 
  mutate(Freq=Deaths/Population*100000)
diabetes_death$State <- fct_reorder(diabetes_death$State,diabetes_death$`State Code`)

diabetes_death %>%
  plot_ly(
    x = ~Percentage, 
    y = ~Freq, 
    color = ~State, 
    frame = ~Year,
    text = ~State, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  )%>%
  animation_opts(
    frame=1000, 
    transition=1000)
```

## Instructions on how to engage
We do an interactive plot between diagnosed diabetes percentage and death rate from 2000 to 2018 by states. 
Visitors can click the legend on right to choose or cancel the state they want, and focus on which state they are interested in. By double-clicking, visitors can select a specific state to view. And by a single click, visitors can add or delete another state.
Visitors can drag the slider at the bottom to view the change by year from 2000 to 2018. Visitors can also click the play button to view the animation change by year.

## Commentary
We can see West Virginia is a very obvious outlier, with a high diagnosed diabetes percentage and high death rate. And the situation in West Virginia is getting worse and worse each year.  

From the animation, we can see the correlation between diagnosed diabetes percentage and death rate changes a lot during the past 18 years. They show a highly positive relationship in the year 2000, and the positive correlation became weaker in the next years. this positive trend may be caused by the technology and medication improvement in recent two decades. Also, people’s awareness of diabetes has raised during these years.

## Limitation and Improvement
There is one issue in this animation, CDC data does not record the percentage of diagnosed diabetes in Hawaii in 2004. So when the animation plays to 2004, Hawaii will disappear from the plot and the other states will have another factor level without Hawaii, so the dots on the plot seems exchanged, while it is actually just reordered without Hawaii.  

We were originally going to add buttons in the plot to let visitors change variables and change plot types. But during the realization, we could not assign new x and y to each button, so we did not accomplish this goal.